version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
    - 5432:5432
  kafka:
    image: wurstmeister/kafka
    hostname: kafka
    ports:
    - "9092:9092"
    environment:
    - KAFKA_ADVERTISED_HOST_NAME=kafka
    - KAFKA_ADVERTISED_PORT=9092
    - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
    - zookeeper
  zookeeper:
    image: wurstmeister/zookeeper
    hostname: zookeeper    
    ports:
    - "2181:2181"
    environment:
    - KAFKA_ADVERTISED_HOST_NAME=zookeeper
  ksql-server:
    image: "confluentinc/cp-ksql-server:5.0.0"
    hostname: ksql-server
    depends_on:
    - kafka
    ports:
    - "8088:8088"
    environment:
      KSQL_BOOTSTRAP_SERVERS: kafka:9092
      KSQL_LISTENERS: http://ksql-server:8088
  ksql-cli:
    image: "confluentinc/cp-ksql-cli:5.0.0"
    hostname: ksql-cli
    depends_on:
    - kafka
    - ksql-server
    entrypoint: /bin/sh
    tty: true